# Generated by Django 5.2 on 2025-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_userprofile_hip_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hip_measurement',
            field=models.FloatField(default=94.0),
        ),
    ]
