# Generated by Django 5.2 on 2025-04-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_userprofile_hip_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessreport',
            name='generated_at',
        ),
    ]
